spring.application.name=kyc-backoffice
server.servlet.session.persistent=false
gg.jte.developmentMode=true
app.totp.enabled=false
# Max size of a single uploaded file
spring.servlet.multipart.max-file-size=10MB

# Max size of the entire multipart request (multiple files + other form data)
spring.servlet.multipart.max-request-size=10MB
