package com.kyc.app.service;

import jakarta.annotation.PostConstruct;
import org.springframework.stereotype.Service;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

@Service
public class ReferenceDataService {

    private Map<String, String> countries;

    @PostConstruct
    public void init() {
        Map<String, String> map = new LinkedHashMap<>();
        map.put("AF", "Afghanistan");
        map.put("AL", "Albania");
        map.put("DZ", "Algeria");
        map.put("AD", "Andorra");
        map.put("AO", "Angola");
        map.put("AG", "Antigua and Barbuda");
        map.put("AR", "Argentina");
        map.put("AM", "Armenia");
        map.put("AU", "Australia");
        map.put("AT", "Austria");
        map.put("AZ", "Azerbaijan");
        map.put("BS", "Bahamas");
        map.put("BH", "Bahrain");
        map.put("BD", "Bangladesh");
        map.put("BB", "Barbados");
        map.put("BY", "Belarus");
        map.put("BE", "Belgium");
        map.put("BZ", "Belize");
        map.put("BJ", "Benin");
        map.put("BT", "Bhutan");
        map.put("BO", "Bolivia");
        map.put("BA", "Bosnia and Herzegovina");
        map.put("BW", "Botswana");
        map.put("BR", "Brazil");
        map.put("BN", "Brunei");
        map.put("BG", "Bulgaria");
        map.put("BF", "Burkina Faso");
        map.put("BI", "Burundi");
        map.put("CV", "Cape Verde");
        map.put("KH", "Cambodia");
        map.put("CM", "Cameroon");
        map.put("CA", "Canada");
        map.put("CF", "Central African Republic");
        map.put("TD", "Chad");
        map.put("CL", "Chile");
        map.put("CN", "China");
        map.put("CO", "Colombia");
        map.put("KM", "Comoros");
        map.put("CG", "Congo");
        map.put("CD", "Congo (Democratic Republic)");
        map.put("CR", "Costa Rica");
        map.put("HR", "Croatia");
        map.put("CU", "Cuba");
        map.put("CY", "Cyprus");
        map.put("CZ", "Czech Republic");
        map.put("DK", "Denmark");
        map.put("DJ", "Djibouti");
        map.put("DM", "Dominica");
        map.put("DO", "Dominican Republic");
        map.put("EC", "Ecuador");
        map.put("EG", "Egypt");
        map.put("SV", "El Salvador");
        map.put("GQ", "Equatorial Guinea");
        map.put("ER", "Eritrea");
        map.put("EE", "Estonia");
        map.put("SZ", "Eswatini");
        map.put("ET", "Ethiopia");
        map.put("FJ", "Fiji");
        map.put("FI", "Finland");
        map.put("FR", "France");
        map.put("GA", "Gabon");
        map.put("GM", "Gambia");
        map.put("GE", "Georgia");
        map.put("DE", "Germany");
        map.put("GH", "Ghana");
        map.put("GR", "Greece");
        map.put("GD", "Grenada");
        map.put("GT", "Guatemala");
        map.put("GN", "Guinea");
        map.put("GW", "Guinea-Bissau");
        map.put("GY", "Guyana");
        map.put("HT", "Haiti");
        map.put("HN", "Honduras");
        map.put("HU", "Hungary");
        map.put("IS", "Iceland");
        map.put("IN", "India");
        map.put("ID", "Indonesia");
        map.put("IR", "Iran");
        map.put("IQ", "Iraq");
        map.put("IE", "Ireland");
        map.put("IL", "Israel");
        map.put("IT", "Italy");
        map.put("JM", "Jamaica");
        map.put("JP", "Japan");
        map.put("JO", "Jordan");
        map.put("KZ", "Kazakhstan");
        map.put("KE", "Kenya");
        map.put("KI", "Kiribati");
        map.put("KP", "Korea (North)");
        map.put("KR", "Korea (South)");
        map.put("KW", "Kuwait");
        map.put("KG", "Kyrgyzstan");
        map.put("LA", "Laos");
        map.put("LV", "Latvia");
        map.put("LB", "Lebanon");
        map.put("LS", "Lesotho");
        map.put("LR", "Liberia");
        map.put("LY", "Libya");
        map.put("LI", "Liechtenstein");
        map.put("LT", "Lithuania");
        map.put("LU", "Luxembourg");
        map.put("MG", "Madagascar");
        map.put("MW", "Malawi");
        map.put("MY", "Malaysia");
        map.put("MV", "Maldives");
        map.put("ML", "Mali");
        map.put("MT", "Malta");
        map.put("MH", "Marshall Islands");
        map.put("MR", "Mauritania");
        map.put("MU", "Mauritius");
        map.put("MX", "Mexico");
        map.put("FM", "Micronesia");
        map.put("MD", "Moldova");
        map.put("MC", "Monaco");
        map.put("MN", "Mongolia");
        map.put("ME", "Montenegro");
        map.put("MA", "Morocco");
        map.put("MZ", "Mozambique");
        map.put("MM", "Myanmar");
        map.put("NA", "Namibia");
        map.put("NR", "Nauru");
        map.put("NP", "Nepal");
        map.put("NL", "Netherlands");
        map.put("NZ", "New Zealand");
        map.put("NI", "Nicaragua");
        map.put("NE", "Niger");
        map.put("NG", "Nigeria");
        map.put("MK", "North Macedonia");
        map.put("NO", "Norway");
        map.put("OM", "Oman");
        map.put("PK", "Pakistan");
        map.put("PW", "Palau");
        map.put("PA", "Panama");
        map.put("PG", "Papua New Guinea");
        map.put("PY", "Paraguay");
        map.put("PE", "Peru");
        map.put("PH", "Philippines");
        map.put("PL", "Poland");
        map.put("PT", "Portugal");
        map.put("QA", "Qatar");
        map.put("RO", "Romania");
        map.put("RU", "Russia");
        map.put("RW", "Rwanda");
        map.put("KN", "Saint Kitts and Nevis");
        map.put("LC", "Saint Lucia");
        map.put("VC", "Saint Vincent and the Grenadines");
        map.put("WS", "Samoa");
        map.put("SM", "San Marino");
        map.put("ST", "Sao Tome and Principe");
        map.put("SA", "Saudi Arabia");
        map.put("SN", "Senegal");
        map.put("RS", "Serbia");
        map.put("SC", "Seychelles");
        map.put("SL", "Sierra Leone");
        map.put("SG", "Singapore");
        map.put("SK", "Slovakia");
        map.put("SI", "Slovenia");
        map.put("SB", "Solomon Islands");
        map.put("SO", "Somalia");
        map.put("ZA", "South Africa");
        map.put("SS", "South Sudan");
        map.put("ES", "Spain");
        map.put("LK", "Sri Lanka");
        map.put("SD", "Sudan");
        map.put("SR", "Suriname");
        map.put("SE", "Sweden");
        map.put("CH", "Switzerland");
        map.put("SY", "Syria");
        map.put("TW", "Taiwan");
        map.put("TJ", "Tajikistan");
        map.put("TZ", "Tanzania");
        map.put("TH", "Thailand");
        map.put("TL", "Timor-Leste");
        map.put("TG", "Togo");
        map.put("TO", "Tonga");
        map.put("TT", "Trinidad and Tobago");
        map.put("TN", "Tunisia");
        map.put("TR", "Turkey");
        map.put("TM", "Turkmenistan");
        map.put("TV", "Tuvalu");
        map.put("UG", "Uganda");
        map.put("UA", "Ukraine");
        map.put("AE", "United Arab Emirates");
        map.put("GB", "United Kingdom");
        map.put("US", "United States");
        map.put("UY", "Uruguay");
        map.put("UZ", "Uzbekistan");
        map.put("VU", "Vanuatu");
        map.put("VA", "Vatican City");
        map.put("VE", "Venezuela");
        map.put("VN", "Vietnam");
        map.put("YE", "Yemen");
        map.put("ZM", "Zambia");
        map.put("ZW", "Zimbabwe");
        this.countries = Collections.unmodifiableMap(map);
    }

    public Map<String, String> getCountries() {
        return countries;
    }
}
